'use strict';

// ─── JSON ─────────────────────────────────────────────────────────────────────
function exportJSON(data) {
  return JSON.stringify(data, null, 2);
}

// ─── Markdown ─────────────────────────────────────────────────────────────────
function exportMarkdown(data, host) {
  const lines = [];
  const now = new Date().toISOString();

  lines.push(`# Sitemap Analysis: ${host}`);
  lines.push('');
  lines.push(`> Generated: ${now}  `);
  lines.push(`> Root: \`${data.rootUrl}\`  `);
  lines.push(`> Total URLs: **${data.totalUrls}**  `);
  lines.push(`> Sitemaps crawled: **${data.totalSitemaps}**`);
  lines.push('');

  // Sitemaps table
  lines.push('## Crawled Sitemaps');
  lines.push('');
  lines.push('| Sitemap URL | URLs | Type | Status |');
  lines.push('|---|---|---|---|');
  for (const s of data.sitemapsFlat) {
    const type = s.isIndex ? '🗂 Index' : '📄 URLset';
    const status = s.error ? `❌ ${s.error}` : '✅ OK';
    lines.push(`| \`${s.url}\` | ${s.urlCount} | ${type} | ${status} |`);
  }
  lines.push('');

  // Tree
  lines.push('## URL Tree Structure');
  lines.push('');
  lines.push('> Leaf groups with 20+ URLs are collapsed — count shown instead of full list.');
  lines.push('');

  renderTreeMd(data.tree, lines, 0);

  lines.push('');
  lines.push('---');
  lines.push('*Generated by Sitemap Analyzer*');

  return lines.join('\n');
}

function renderTreeMd(node, lines, depth) {
  if (node.name === '/' && depth === 0) {
    lines.push(`**/** — ${node.totalCount} URLs`);
    for (const child of node.children) renderTreeMd(child, lines, depth + 1);
    return;
  }

  const indent = '  '.repeat(depth);
  const icon = node.children.length > 0 ? '📁' : '📄';
  lines.push(`${indent}- ${icon} **/${node.name}** — ${node.totalCount} URLs`);

  if (node.isLeafGroup && node.collapsed) {
    lines.push(`${indent}  - *(${node.directUrlCount} конечных URL — список свёрнут)*`);
  } else if (node.isLeafGroup) {
    for (const u of node.directUrls) {
      lines.push(`${indent}  - \`${u.loc}\``);
    }
  }

  for (const child of node.children) renderTreeMd(child, lines, depth + 1);
}

module.exports = { exportJSON, exportMarkdown };
