/* generated by scripts/build-prompts-data.cjs */
(function () {
  window.PROMPTS = [
  {
    "id": "meta-title-commercial",
    "category": "Мета-теги",
    "subcategory": "Title",
    "title": "Title для коммерческой страницы",
    "description": "Кликабельный title 50–60 знаков, ключ + город + УТП.",
    "tags": [
      "title",
      "к",
      "услуги"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{ключ}}",
      "{{город}}",
      "{{УТП}}"
    ],
    "prompt": "Ты SEO-копирайтер. Составь 5 вариантов title (50–60 знаков) для коммерческой страницы. Ключ: {{ключ}}. Город/регион: {{город}}. УТП/оффер: {{УТП}}. Ключ в первой половине, без капса и переспама. Нумерованный список.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "meta-title-article",
    "category": "Мета-теги",
    "subcategory": "Title",
    "title": "Title для статьи / блога",
    "description": "Интрига и ключ без кликбейта.",
    "tags": [
      "title",
      "статья"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{тема}}",
      "{{вопрос}}"
    ],
    "prompt": "Напиши 4 варианта title 55–60 знаков. Тема: {{тема}}. Уточнение или вопрос: {{вопрос}}. Естественный язык, цифра или год по месту, без «шок!».",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "meta-title-category",
    "category": "Мета-теги",
    "subcategory": "Title",
    "title": "Title для категории каталога",
    "description": "Фильтры, вложенность, бренд.",
    "tags": [
      "категория",
      "фильтр"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{категория}}",
      "{{фильтры}}"
    ],
    "prompt": "Создай 3 варианта title (до 60 знаков) для категории «{{категория}}» с учётом фильтров: {{фильтры}}. Без дублирования «категория», не перегружай списком.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "meta-title-audit",
    "category": "Мета-теги",
    "subcategory": "Title",
    "title": "Аудит существующего Title",
    "description": "Сравнение с конкурентом по смыслу не нужно — только текст.",
    "tags": [
      "аудит",
      "title"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{текущий_title}}",
      "{{ключ}}"
    ],
    "prompt": "Title сейчас: «{{текущий_title}}». Ключ: {{ключ}}. Оцени длину, позицию ключа, CTR. Дай 3 переписанных варианта + по одной причине на вариант.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "meta-desc-commercial",
    "category": "Мета-теги",
    "subcategory": "Description",
    "title": "Description для коммерческой",
    "description": "150–160 знаков, CTA, ключ в начале.",
    "tags": [
      "description",
      "к"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{ключ}}",
      "{{город}}",
      "{{CTA}}"
    ],
    "prompt": "Meta description 150–160 знаков. Ключ {{ключ}} в первых 120 знаках, город {{город}}, CTA: {{CTA}}. 1 USP, без капса.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "meta-desc-article",
    "category": "Мета-теги",
    "subcategory": "Description",
    "title": "Description для статьи",
    "description": "Соответствие интенту и сниппету.",
    "tags": [
      "description",
      "статья"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{тема}}",
      "{{крючек}}"
    ],
    "prompt": "Два варианта description до 160 знаков. Тема: {{тема}}. Крючок/обещание: {{крючек}}. Без вводного «в статье…» в первых 20 символов.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "meta-desc-category",
    "category": "Мета-теги",
    "subcategory": "Description",
    "title": "Description для категории",
    "description": "Категория + USP, без копии title.",
    "tags": [
      "description",
      "категория"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{категория}}",
      "{{USP}}"
    ],
    "prompt": "Описание 155–160 знаков для категории «{{категория}}» с УТП: {{USP}}. Упомяни доставку/цены, если в УТП не сказано — не выдумывай, используй плейсхолдеры.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "meta-desc-audit",
    "category": "Мета-теги",
    "subcategory": "Description",
    "title": "Аудит существующего Description",
    "description": "Переспам, вода, длина.",
    "tags": [
      "description",
      "аудит"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{текущий}}",
      "{{ключ}}"
    ],
    "prompt": "Текущее description: «{{текущий}}», ключ: {{ключ}}. Укажи нарушения, целевую длину, 2 переписанных варианта.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "meta-robots-rules",
    "category": "Мета-теги",
    "subcategory": "Robots / Canonical",
    "title": "Написать Robots meta для страницы",
    "description": "noindex, nofollow, noarchive.",
    "tags": [
      "robots",
      "index"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{тип_страницы}}"
    ],
    "prompt": "Тип страницы: {{тип_страницы}}. Подбери оптимальное meta robots, объясни, когда нужен noindex+follow, дай тег.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "meta-canonical-check",
    "category": "Мета-теги",
    "subcategory": "Robots / Canonical",
    "title": "Проверить и объяснить canonical",
    "description": "Самореференс, пагинация, дубли.",
    "tags": [
      "canonical",
      "url"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{url}}"
    ],
    "prompt": "URL: {{url}}. Нужен ли self-canonical, пагинация, trailing slash, www. Схема в 4 пункта + пример link.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "meta-og-twitter",
    "category": "Мета-теги",
    "subcategory": "Open Graph / Twitter",
    "title": "Open Graph + Twitter Card",
    "description": "Превью в соцсетях и мессенджерах",
    "tags": [
      "og",
      "twitter",
      "мета"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{заголовок}}",
      "{{url}}",
      "{{описание}}",
      "{{картинка}}"
    ],
    "prompt": "Собери набор тегов og:title, og:description, og:url, og:image, og:type, а также twitter:card (summary_large_image), twitter:title, twitter:description, twitter:image. Данные: заголовок «{{заголовок}}», url {{url}}, описание {{описание}}, image URL {{картинка}}. Выведи готовый HTML фрагмент (meta), без <body>.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "schema-faq",
    "category": "Структурированные данные",
    "subcategory": "FAQ",
    "title": "FAQ Schema из вопросов и ответов",
    "description": "JSON-LD FAQPage",
    "tags": [
      "schema",
      "faq"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{q_and_a_список}}"
    ],
    "prompt": "Сформируй валидный JSON-LD FAQPage для Google. Вопрос-ответ: {{q_and_a_список}}. Только JSON-LD в script type=application/ld+json, без markdown.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "schema-faq-from-text",
    "category": "Структурированные данные",
    "subcategory": "FAQ",
    "title": "Сгенерировать FAQ из текста страницы",
    "description": "Извлечь пары Q/A",
    "tags": [
      "schema",
      "faq"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{текст}}"
    ],
    "prompt": "Из текста извлеки 5–8 пар вопрос-ответ для FAQ, затем JSON-LD FAQPage. Текст: {{текст}}",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "schema-localbusiness",
    "category": "Структурированные данные",
    "subcategory": "LocalBusiness",
    "title": "LocalBusiness Schema",
    "description": "NAP, часы, зона",
    "tags": [
      "local",
      "schema"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{название}}",
      "{{адрес}}",
      "{{телефон}}",
      "{{услуги}}"
    ],
    "prompt": "JSON-LD LocalBusiness: название {{название}}, адрес {{адрес}}, телефон {{телефон}}, услуги: {{услуги}}. Добавь @id и openingHours, если нет — опиши поля-заглушки.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "schema-localbusiness-audit",
    "category": "Структурированные данные",
    "subcategory": "LocalBusiness",
    "title": "Аудит существующей LocalBusiness",
    "description": "Ошибки и обязательные поля.",
    "tags": [
      "schema",
      "аудит"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{json_ld}}"
    ],
    "prompt": "Проверь JSON-LD: {{json_ld}}. Список ошибок, обязательные поля Google, и исправленный фрагмент.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "schema-breadcrumb",
    "category": "Структурированные данные",
    "subcategory": "BreadcrumbList",
    "title": "BreadcrumbList из URL-пути",
    "description": "ItemList, position",
    "tags": [
      "breadcrumb"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{url}}",
      "{{названия_разделов}}"
    ],
    "prompt": "Построй BreadcrumbList: URL {{url}}, подписи уровней: {{названия_разделов}}. JSON-LD одним блоком.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "schema-product",
    "category": "Структурированные данные",
    "subcategory": "Product / Offer",
    "title": "Product + Offer Schema",
    "description": "Цена, валюта, availability",
    "tags": [
      "product",
      "schema"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{товар}}",
      "{{цена}}",
      "{{валюта}}"
    ],
    "prompt": "JSON-LD Product+Offer: товар «{{товар}}», цена {{цена}} {{валюта}}, availability, condition.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "schema-article",
    "category": "Структурированные данные",
    "subcategory": "Article / BlogPosting",
    "title": "Article Schema для блога",
    "description": "headline, author, date",
    "tags": [
      "article"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{заголовок}}",
      "{{автор}}",
      "{{дата}}"
    ],
    "prompt": "JSON-LD Article: headline «{{заголовок}}», author {{автор}}, datePublished {{дата}}, publisher placeholder.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "schema-howto",
    "category": "Структурированные данные",
    "subcategory": "HowTo",
    "title": "HowTo Schema из инструкции",
    "description": "HowToStep",
    "tags": [
      "howto",
      "schema"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{текст_инструкции}}"
    ],
    "prompt": "Разбей «{{текст_инструкции}}» на шаги, JSON-LD HowTo + HowToStep.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "schema-review",
    "category": "Структурированные данные",
    "subcategory": "Review",
    "title": "AggregateRating из отзывов",
    "description": "Средняя, count",
    "tags": [
      "review"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{отзывы}}"
    ],
    "prompt": "По сырым отзывам {{отзывы}} посчитай агрегат и JSON-LD AggregateRating + Review, если данных мало — опиши допущения.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "schema-audit-full",
    "category": "Структурированные данные",
    "subcategory": "JSON-LD",
    "title": "Аудит всей JSON-LD разметки страницы",
    "description": "Конфликты типов",
    "tags": [
      "schema",
      "аудит"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{все_схемы}}"
    ],
    "prompt": "Перечисли схемы: {{все_схемы}}. Конфликты @id, дубли типов, рекомендации единой graph.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-html5-page",
    "category": "Контент",
    "subcategory": "HTML5-разметка",
    "title": "Написать HTML5-разметку страницы",
    "description": "Семантика main, section, article",
    "tags": [
      "html5"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{тип_страницы}}",
      "{{ключ}}",
      "{{структура}}"
    ],
    "prompt": "Скелет HTML5: тип {{тип_страницы}}, ключ {{ключ}}, структура блоков: {{структура}}. Один h1, логичные h2, без style inline.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-html5-article",
    "category": "Контент",
    "subcategory": "HTML5-разметка",
    "title": "Семантическая разметка статьи",
    "description": "article, time, author",
    "tags": [
      "html5",
      "статья"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{заголовок}}",
      "{{разделы}}"
    ],
    "prompt": "HTML5-скелет статьи: заголовок «{{заголовок}}», план разделов {{разделы}}. time, address автора, aside для связанного.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-html5-audit",
    "category": "Контент",
    "subcategory": "HTML5-разметка",
    "title": "Аудит HTML5-семантики страницы",
    "description": "Лишние div, h1",
    "tags": [
      "аудит",
      "html"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{html_код}}"
    ],
    "prompt": "HTML: {{html_код}}. Проблемы: несколько h1, div soup, ARIA. Список и патч-рекомендации.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-text-commercial",
    "category": "Контент",
    "subcategory": "Текст страницы",
    "title": "Текст для коммерческой страницы",
    "description": "H2-H3, УТП, CTA",
    "tags": [
      "текст",
      "к"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{услуга}}",
      "{{город}}",
      "{{аудитория}}"
    ],
    "prompt": "Напиши текст 2–3 тыс. знаков: услуга {{услуга}}, город {{город}}, ЦА: {{аудитория}}. H2 с ключом, CTA, без воды.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-text-category",
    "category": "Контент",
    "subcategory": "Текст страницы",
    "title": "Текст для страницы категории",
    "description": "Обзор + подкатегории",
    "tags": [
      "текст",
      "категория"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{категория}}",
      "{{топ_ключи}}"
    ],
    "prompt": "Текст категории: {{категория}}, ключи-спутники: {{топ_ключи}}. Ввод, блоки, ссылки-заглушки #, FAQ мини-3.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-text-silo",
    "category": "Контент",
    "subcategory": "Текст страницы",
    "title": "Текст с учётом сайлинга",
    "description": "Связь с соседями",
    "tags": [
      "silo",
      "текст"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{тема}}",
      "{{соседние_страницы}}"
    ],
    "prompt": "Тема: {{тема}}. Соседние URL/темы: {{соседние_страницы}}. Вплети 3–4 внутренние ссылки якорями, без переспама.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-article-full",
    "category": "Контент",
    "subcategory": "Статья / Блог",
    "title": "Полноформатная SEO-статья",
    "description": "Структура, E-E-A-T",
    "tags": [
      "статья",
      "longread"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{тема}}",
      "{{ключи}}",
      "{{структура_h2}}"
    ],
    "prompt": "Статья: тема {{тема}}, кластер ключей: {{ключи}}, план H2: {{структура_h2}}. Введение, основная часть, вывод, чек-лист, мета-описание в конце.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-article-rewrite",
    "category": "Контент",
    "subcategory": "Статья / Блог",
    "title": "Переписать статью под SEO",
    "description": "Семантическое ядро",
    "tags": [
      "rewrite"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{исходный_текст}}",
      "{{ключи}}"
    ],
    "prompt": "Исходник: {{исходный_текст}}. Ключи: {{ключи}}. Сохрани смысл, улучшай структуру H2, введи LSI, убери воду.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-article-brief",
    "category": "Контент",
    "subcategory": "Статья / Блог",
    "title": "Бриф для статьи",
    "description": "Для копирайтера",
    "tags": [
      "бриф"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{тема}}",
      "{{конкуренты}}"
    ],
    "prompt": "Составь бриф: {{тема}}. Ссылки на 3–5 «конкурентов» по смыслу: {{конкуренты}}. Целевая длина, H2, уникальное УТП, запреты.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-commercial-cta",
    "category": "Контент",
    "subcategory": "Коммерческий текст",
    "title": "Написать CTA-блок",
    "description": "Три варианта тона",
    "tags": [
      "CTA"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{услуга}}",
      "{{боль}}",
      "{{оффер}}"
    ],
    "prompt": "3 варианта CTA: услуга {{услуга}}, боль: {{боль}}, оффер: {{оффер}}. Короткие, для кнопок и футеров.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-commercial-usp",
    "category": "Контент",
    "subcategory": "Коммерческий текст",
    "title": "Блок преимуществ / УТП",
    "description": "3–5 буллетов + раскрытие",
    "tags": [
      "USP"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{услуга}}",
      "{{факты}}"
    ],
    "prompt": "Список УТП для {{услуга}}. Факты: {{факты}}. Буллеты 80–100 знаков, цифры, без ложных суперлативов.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-commercial-price",
    "category": "Контент",
    "subcategory": "Коммерческий текст",
    "title": "Текст для прайс-страницы",
    "description": "Таблица + дисклеймер",
    "tags": [
      "прайс"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{услуга}}",
      "{{цены}}"
    ],
    "prompt": "Прайс: услуга {{услуга}}, тарифы/цифры: {{цены}}. Вводный абзац, таблица markdown, сноска о «от» и сроке актуальности.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-audit-text",
    "category": "Контент",
    "subcategory": "Аудит",
    "title": "SEO-аудит текста страницы",
    "description": "Ключ, тошнота",
    "tags": [
      "аудит"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{текст}}",
      "{{ключ}}"
    ],
    "prompt": "Текст: {{текст}}. Ключ: {{ключ}}. Плотность, семантика, вода, дубли, рекомендации по абзацам.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-audit-structure",
    "category": "Контент",
    "subcategory": "Аудит",
    "title": "Аудит структуры заголовков",
    "description": "Дерево H1–H6",
    "tags": [
      "заголовки"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{h1_h6_дерево}}"
    ],
    "prompt": "Дерево: {{h1_h6_дерево}}. Анализ вложенности, каннибализация, пересечения с кластером, скелет исправлений.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "content-product-card",
    "category": "Контент",
    "subcategory": "E-commerce",
    "title": "Описание карточки товара",
    "description": "Характеристики, УТП, доставка",
    "tags": [
      "товар",
      "ecom"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{название}}",
      "{{характеристики}}",
      "{{аудитория}}"
    ],
    "prompt": "Составь продающее описание 800–1500 зн: товар «{{название}}», характеристики: {{характеристики}}, ЦА: {{аудитория}}. Без запрещённых приёмов (ложные скидки). H3 подблоки, CTA, FAQ мини-2.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "tech-audit-page",
    "category": "Технический SEO",
    "subcategory": "Аудит страницы",
    "title": "Технический аудит одной страницы",
    "description": "Meta, LCP, links",
    "tags": [
      "тех. аудит"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{url}}",
      "{{html}}",
      "{{мета}}"
    ],
    "prompt": "Вход: URL {{url}}, HTML-фрагмент {{html}}, известные мета {{мета}}. Чеклист: indexability, LCP, dupl, mixed content — таблицей.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "tech-audit-checklist",
    "category": "Технический SEO",
    "subcategory": "Чеклист",
    "title": "Чеклист по технической оптимизации",
    "description": "По слоям: crawl, index,",
    "tags": [
      "чеклист"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{cms}}",
      "{{тип_сайта}}"
    ],
    "prompt": "Сайт на {{cms}}, тип: {{тип_сайта}}. 25 пунктов чеклиста с приоритетом 1/2/3.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "tech-audit-core-web",
    "category": "Технический SEO",
    "subcategory": "Core Web Vitals",
    "title": "Рекомендации по Core Web Vitals",
    "description": "LCP, INP, CLS",
    "tags": [
      "CWV"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{метрики}}",
      "{{cms}}"
    ],
    "prompt": "Метрики: {{метрики}}, CMS {{cms}}. Для каждой метрики: причина, 3 fix-а, приоритет.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "tech-robots-txt",
    "category": "Технический SEO",
    "subcategory": "Robots.txt / Sitemap",
    "title": "Написать robots.txt",
    "description": "Правила, Host",
    "tags": [
      "robots"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{cms}}",
      "{{важные_разделы}}",
      "{{закрыть}}"
    ],
    "prompt": "CMS: {{cms}}. Нельзя: {{закрыть}}. Важно открыть: {{важные_разделы}}. Готовый robots.txt, комменты #.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "tech-sitemap-strategy",
    "category": "Технический SEO",
    "subcategory": "Robots.txt / Sitemap",
    "title": "Стратегия sitemap для крупного сайта",
    "description": "Индексация, чанки",
    "tags": [
      "sitemap"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{кол_страниц}}",
      "{{структура}}"
    ],
    "prompt": "~{{кол_страниц}} страниц, структура: {{структура}}. План: индексы, лимит URL, lastmod, пинг.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "tech-redirect-strategy",
    "category": "Технический SEO",
    "subcategory": "Переезды",
    "title": "Стратегия редиректов при переезде",
    "description": "301, цепочки",
    "tags": [
      "редирект"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{старая_структура}}",
      "{{новая_структура}}"
    ],
    "prompt": "Старая: {{старая_структура}}. Новая: {{новая_структура}}. Матчинг путей, 410, 301-цепочки, GSC.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "tech-hreflang",
    "category": "Технический SEO",
    "subcategory": "Мультиязыч",
    "title": "Написать hreflang теги",
    "description": "x-default",
    "tags": [
      "hreflang"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{страны}}",
      "{{url_шаблон}}"
    ],
    "prompt": "Регионы/языки: {{страны}}. URL-шаблон: {{url_шаблон}}. Пары link rel=alternate, x-default, примеры.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "tech-page-speed",
    "category": "Технический SEO",
    "subcategory": "Скорость",
    "title": "Рекомендации по скорости страницы",
    "description": "Waterfall, third-party",
    "tags": [
      "скорость"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{waterfall}}",
      "{{cms}}"
    ],
    "prompt": "Сводка waterfall: {{waterfall}}, CMS {{cms}}. Defer, preload, image lazy, критичный CSS.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "links-anchor-texts",
    "category": "Внутренняя перелинковка",
    "subcategory": "Анкоры",
    "title": "Анкоры для внутренних ссылок",
    "description": "Семантика, разнообразие",
    "tags": [
      "анкор"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{страница}}",
      "{{ключи}}"
    ],
    "prompt": "Целевая {{страница}}, кластер: {{ключи}}. 10 вариантов анкоров, без одинаковых подряд.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "links-silo-map",
    "category": "Внутренняя перелинковка",
    "subcategory": "Сайлинг",
    "title": "Карта сайлинга для раздела",
    "description": "Сетевой граф",
    "tags": [
      "silo"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{раздел}}",
      "{{страницы}}"
    ],
    "prompt": "Раздел {{раздел}}. Список страниц: {{страницы}}. Mermaid-описание или таблица «клиент → хабы».",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "links-footer-nav",
    "category": "Внутренняя перелинковка",
    "subcategory": "Навигация",
    "title": "Структура footer-навигации",
    "description": "Кластерные блоки",
    "tags": [
      "footer"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{тематика}}",
      "{{разделы}}"
    ],
    "prompt": "Тематика {{тематика}}, разделы: {{разделы}}. 3–4 колонки ссылок, баланс коммерция/инфо, nofollow — где уместен.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "links-audit",
    "category": "Внутренняя перелинковка",
    "subcategory": "Аудит",
    "title": "Аудит внутренней перелинковки",
    "description": "Сироты, дубли",
    "tags": [
      "аудит",
      "link"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{список_страниц}}"
    ],
    "prompt": "Страницы: {{список_страниц}}. Сироты, перелинковка на главную, кластеры, рекомендации 5+ действий.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "comp-gap-analysis",
    "category": "Анализ конкурентов",
    "subcategory": "Контент-гэп",
    "title": "Анализ контент-гэпа",
    "description": "Темы, форматы",
    "tags": [
      "gap"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{мои_страницы}}",
      "{{страницы_конкурента}}"
    ],
    "prompt": "Мои URL: {{мои_страницы}}. Конкурент: {{страницы_конкурента}}. Матрица: тема × у кого сильнее, приоритеты.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "comp-title-compare",
    "category": "Анализ конкурентов",
    "subcategory": "Title",
    "title": "Сравнение Title с топ-10",
    "description": "Паттерны, длина",
    "tags": [
      "title"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{мой_title}}",
      "{{топ_10_title}}"
    ],
    "prompt": "Мой: «{{мой_title}}». Топ: {{топ_10_title}}. Таблица: длина, ключ, модификатор. 3 варианта улучшения.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "comp-schema-compare",
    "category": "Анализ конкурентов",
    "subcategory": "Schema",
    "title": "Сравнение схем с конкурентами",
    "description": "Недостающие type",
    "tags": [
      "schema"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{мои_схемы}}",
      "{{схемы_конкурентов}}"
    ],
    "prompt": "Мои схемы: {{мои_схемы}}. У конкурентов: {{схемы_конкурентов}}. Чеклист: что внедрить первым.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "comp-snippet-improve",
    "category": "Анализ конкурентов",
    "subcategory": "Сниппет",
    "title": "Улучшить сниппет под конкурентов",
    "description": "Rich results",
    "tags": [
      "сниппет"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{мой_сниппет}}",
      "{{топ_сниппеты}}"
    ],
    "prompt": "Мой сниппет: {{мой_сниппет}}. Примеры топа: {{топ_сниппеты}}. Микроразметка, sitelinks, CTA.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "local-gmb-description",
    "category": "Локальное SEO",
    "subcategory": "GMB",
    "title": "Описание для Google My Business",
    "description": "700 символов, policy",
    "tags": [
      "GMB",
      "local"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{бизнес}}",
      "{{услуги}}",
      "{{город}}"
    ],
    "prompt": "Название/тип: {{бизнес}}. Услуги: {{услуги}}. Город {{город}}. Описание 700 зн, без ссылок/тел, без promos, уникально.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "local-landing-text",
    "category": "Локальное SEO",
    "subcategory": "Гео-лендинг",
    "title": "Текст для гео-лендинга",
    "description": "Район + ключ",
    "tags": [
      "local"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{услуга}}",
      "{{город}}",
      "{{район}}"
    ],
    "prompt": "Услуга {{услуга}}, {{город}}, район {{район}}. 2k знаков, блок «как проехать», NAP, микроразметка LocalBusiness.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "local-nap-consistency",
    "category": "Локальное SEO",
    "subcategory": "NAP",
    "title": "Проверить NAP-консистентность",
    "description": "Справочники",
    "tags": [
      "NAP"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{нейм}}",
      "{{адрес}}",
      "{{телефон}}",
      "{{источники}}"
    ],
    "prompt": "Данные: {{нейм}}, {{адрес}}, {{телефон}}. Сверка с: {{источники}}. Таблица расхождений, приоритет правки.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  },
  {
    "id": "local-reviews-reply",
    "category": "Локальное SEO",
    "subcategory": "Отзывы",
    "title": "Ответить на отзывы",
    "description": "Тон, бренд",
    "tags": [
      "отзывы"
    ],
    "model": [
      "ChatGPT",
      "Claude",
      "Gemini"
    ],
    "variables": [
      "{{отзыв}}",
      "{{тон}}",
      "{{бизнес}}"
    ],
    "prompt": "Отзыв: «{{отзыв}}». Тон: {{тон}}. Бизнес: {{бизнес}}. 2 варианта ответа, 100–200 зн, gratitude + action.",
    "example_input": "Пример: заполни переменные краткими фразами, как в брифе.",
    "example_output": "Пример: релевантный ответ нейросети в 1–3 предложения.",
    "updated": "2026-04",
    "author": "seohead.tech"
  }
];
})();
